# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('asset_type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
