# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsBorrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Assets')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
